Carpeta donde estarán los archivos del XBlock y el archivo readme par…
J4ckDev/XBlock-Estilos-de-Aprendizaje pull request #1
Opened 2020-11-17 21:23 UTC by githubleandro

…a el XBlock generado

2020-11-18 23:06 UTC, J4ckDev reviewed
Solo se debe realizar un cambio menor en la función de Honey-Alonso, por lo demás funcionó correctamente en las pruebas realizadas

2020-11-18 23:06 UTC, J4ckDev commented on TEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue"> TEST HONEY-ALONSO </div> <p class="">Este cuestionario no ha sido d
La pregunta 19 tiene repetido su texto 2 veces, las preguntas 22 y 25 tienen la letra r de sobra.

2020-11-18 23:14 UTC, J4ckDev reviewed
Arreglar los detalles de student_adaptive_test.js

2020-11-18 23:58 UTC, J4ckDev requested changes
Corregir lo anteriormente mencionado

2020-11-19 00:51 UTC, J4ckDev approved these changes
Cambios realizados correctamente.

2020-11-24 15:04 UTC, dsrestrepo approved these changes

2020-11-25 14:46 UTC, J4ckDev requested changes

2020-11-25 14:46 UTC, J4ckDev commented on TEA/adaptive_test/adaptive_test/adaptive_test.py
> +        cur.execute("INSERT INTO resultadostest (fecha, nombre_test, resultado) VALUES (CURRENT_DATE,%s, %s)", (data['test_name'], data['result']))
Agregar el ID para quitar el valor autoincremental en la base de datos

2020-12-03 14:41 UTC, J4ckDev approved these changes

2020-12-03 14:41 UTC, merged