Smea
J4ckDev/XBlock-Estilos-de-Aprendizaje pull request #2
Opened 2020-11-17 21:27 UTC by kevinmuz55

2020-11-18 23:43 UTC, J4ckDev reviewed
No hay procesamiento de la información

2020-11-18 23:43 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +
No crearon la función que procesa la respuesta del estudiante, para dar el resultado del test de Honey-Alonso

2020-11-18 23:53 UTC, J4ckDev reviewed
Arreglar la aplicación de estilos CSS

2020-11-18 23:53 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
cambiar las clases CSS para que se vea de una mejor forma el Xblock para mostrar el test de Honey-Alonso

2020-11-18 23:55 UTC, J4ckDev reviewed
Revisión finalizada.

2020-11-19 00:00 UTC, J4ckDev commented
Lo realizado por el equipo 2 estuvo mejor realizado.

2020-11-19 00:17 UTC, kevinmuz55 commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +
Correcto, dado que los resultados ya tiene que entenderse con una parte más de backend y almacenamiento de datos, pero eso se haría localmente o con Ajax

2020-11-19 00:19 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +
Sí es la labor del equipo 2, una confusión mía

2020-11-19 00:23 UTC, J4ckDev requested changes
Arreglen la forma en la que se muestra el test de Honey Alonso en el archivo student_adaptive_test.js, se ven muy apeñuscadas las preguntas.

2020-11-19 00:25 UTC, kevinmuz55 commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
De acuerdo, pensábamos que el estilo tenia que ser el mismo en todos los test

2020-11-19 00:28 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
Es el mismo, pero por alguna razón aparece diferente a los otros.

2020-11-19 00:37 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
# Así aparece el de Honey Alonso
![Captura de pantalla de 2020-11-18 19-33-26](https://user-images.githubusercontent.com/37965481/99605168-23c7c680-29d5-11eb-8202-63d1b7d50614.png)

 ## El de dominancia cerebral aparece así:
![Captura de pantalla de 2020-11-18 19-34-20](https://user-images.githubusercontent.com/37965481/99605165-232f3000-29d5-11eb-8e14-da4ad326bbf7.png)

## Y el de Kolb aparece así
![Captura de pantalla de 2020-11-18 19-33-48](https://user-images.githubusercontent.com/37965481/99605167-23c7c680-29d5-11eb-9fa5-1e0a0accb936.png)

2020-11-19 00:37 UTC, kevinmuz55 commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
Entendido

2020-11-19 03:25 UTC, kevinmuz55 commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
Se cambio el estilo css implementando bootstrap

2020-11-19 03:59 UTC, J4ckDev requested changes
Encontré que el test de Honey Alonso no tiene una forma de comprobar que fue respondido completamente, lo dejé a medias y envió el formulario con más de la mitad de preguntas sin responder. Agregar también una forma de validar que fueron respondidas todas las preguntas.

2020-11-19 03:59 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer" class="card d-flex justify-content-center" > <div class="container-fluid "> <div class="bg-primary  d-flex justify-content-center">  <h1 class="h1 text-white">
En la pregunta 41 el último fragmento dice "pensando en el paso o en el futuro", asumo que debería decir "pensando en el pasado o en el futuro", si es así corregir.

2020-11-19 04:02 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer"> <div class="container z-depth-5"> <!-- Page Content goes here --> <div class="card-panel teal light-blue center-align flow-text white-text text-light-blue">TE
Me gustó

2020-11-19 19:51 UTC, kevinmuz55 commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer" class="card d-flex justify-content-center" > <div class="container-fluid "> <div class="bg-primary  d-flex justify-content-center">  <h1 class="h1 text-white">
Con respecto a la pregunta 41 si se habia presentado un error, se corrigió.

Ahora bien, dado que el envio de la informacion se lleva a cabo fuera del html del cuestionario como tal, no se encontró manera de validar las respuestas, por lo que se obtó por llenar todos los campos de manera positiva, así siempre estará lleno el cuestionario.

2020-11-19 19:55 UTC, J4ckDev commented on SMEA/adaptive_test/adaptive_test/static/js/src/student_adaptive_test.js
> +        html = '<div id="testContainer" class="card d-flex justify-content-center" > <div class="container-fluid "> <div class="bg-primary  d-flex justify-content-center">  <h1 class="h1 text-white">
Vale compañero, sube los cambios realizados.

2020-11-19 20:12 UTC, J4ckDev approved these changes
Revisión finalizada y cambios aceptados.

2020-11-24 15:05 UTC, dsrestrepo approved these changes

2020-11-24 15:37 UTC, merged