Cr
J4ckDev/XBlock-Estilos-de-Aprendizaje pull request #3
Opened 2020-11-21 16:55 UTC by camilo-burbano

2020-11-24 15:04 UTC, dsrestrepo approved these changes

2020-11-24 15:27 UTC, dsrestrepo commented on CR/myxblock/myxblock/myxblock.py
> +        cur.execute("SELECT valor FROM graficar")
Aquí lo único seria cambiar el nombre de **valores** de su base de datos a **resultado** para tener todos la misma base de datos; los campos acordados fueron: Id_curso:Integer, Id:estudiante:Integer[PK], fecha:date, nombre_test: character varying(30), resultado:character varying(30)

2020-11-25 15:14 UTC, J4ckDev requested changes
Además de la notación de David, arreglar estos nuevos cambios

2020-11-25 15:14 UTC, J4ckDev commented on CR/myxblock/myxblock/static/js/src/studio_view.js
> +    o = Math.floor(((a * 100) / z) * 100) / 100;
Generalizar para todos los estilos de aprendizaje

2020-11-25 15:14 UTC, J4ckDev commented on CR/myxblock/myxblock/static/js/src/studio_view.js
> +    var grafica = document.getElementById('grafico').getContext('2d');
Quitar el diagrama de pastel y solo dejar el de barras

2020-12-09 19:37 UTC, J4ckDev approved these changes

2020-12-10 18:24 UTC, merged